table 'Budget Target'
	lineageTag: 09cc3b1c-e053-4ebb-9e62-37a6cbd4cd75

	column Store
		dataType: string
		lineageTag: f602cf30-9145-4c30-af9d-4ee6845f0bf0
		summarizeBy: none
		sourceColumn: Store

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: cfb75175-beec-4d4e-b85f-99dec325da4d
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd704ce2-6441-4ee2-aa50-504b7234febe
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Qty
		dataType: double
		lineageTag: 16123f33-73ef-4155-8241-6be1ca44ced7
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Combine
		dataType: string
		lineageTag: 734016b9-244c-4a9e-92c3-09dc55c9ecee
		summarizeBy: none
		sourceColumn: Combine

		annotation SummarizationSetBy = Automatic

	column 'Cost Value' = [Qty]/2.4
		dataType: double
		lineageTag: 7cc300ed-25fb-4167-abdc-8d58b15f8e64
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Tax' = IF([Brand]="Outfitters",[Qty]*0.12,[Qty]*0.12)
		dataType: double
		lineageTag: f0e549eb-f8f2-48a7-91cd-cf2df17dda0d
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Budget Target-407c805f-2376-41af-934b-d47bdecf52a6' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Outfitters Stores\BI-Upload - Documents\PP DATA\COMBINE\Day wise Budgeted Targets.xlsx"), null, true),
				    #"Budget Target_Sheet" = Source{[Item="Budget Target",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Budget Target_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Store", type text}, {"Brand", type text}, {"Date", type date}, {"Qty", type number}, {"Column5", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Column5"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Combine", each [Store]&[Brand]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Combine", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

