table 'Budgeted GP'
	lineageTag: d1ede1f7-3ff5-4395-ab86-d47122497609

	column 'Store Name'
		dataType: string
		lineageTag: 9bb24b8d-fe54-4100-9297-5ee4f85da358
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: aa611f25-a15e-46ca-8ab8-7ab4e83df5be
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f979e478-6662-45a7-bd38-c3e90a517b0f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: double
		lineageTag: 8e76ae6a-24ba-47c3-9074-61397f4d49d8
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Combine
		dataType: string
		lineageTag: 98ec891d-2416-4f05-b307-a7112e3aa00e
		summarizeBy: none
		sourceColumn: Combine

		annotation SummarizationSetBy = Automatic

	partition 'Budgeted GP-b5b81141-7662-4d67-885c-bc5eabf277b7' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Outfitters Stores\BI-Upload - Documents\PP DATA\COMBINE\Day wise Budgeted GP.xlsx"), null, true),
				    JUL_20_OFT_Table = Source{[Item="JUL_20_OFT",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(JUL_20_OFT_Table,{{"Store Name", type text}, {"Brand", type text}, {"Date", type date}, {"Value", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Combine", each [Store Name]&[Brand]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Combine", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

