table Images_1
	lineageTag: 346d431e-e2fc-4fc2-a7f9-5f9096a61ce3

	column 'Icon Name'
		dataType: string
		lineageTag: e3b92e7f-2878-427e-877a-0a8b815d31d5
		summarizeBy: none
		sourceColumn: Icon Name

		annotation SummarizationSetBy = Automatic

	column 'Image Urls'
		dataType: string
		lineageTag: 6abe6d1d-8925-4572-950b-e130efca3a17
		summarizeBy: none
		sourceColumn: Image Urls

		annotation SummarizationSetBy = Automatic

	partition Images_1-30927797-a44b-456f-ac90-806535060e7f = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Outfitters Stores\BI-Upload - Documents\PP DATA\COMBINE\images_Url.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet1_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Icon Name", type text}, {"Image Urls", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

