table Kit
	lineageTag: 59dc93f2-afd6-47c9-8650-974388dbeb09

	column Style
		dataType: string
		lineageTag: a85b99fe-5ea6-40a0-b4c5-ef85905bc137
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 600ab295-7af5-43cb-a6d2-988acf613f49
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	partition Kit-8f261ef4-7575-467a-81c4-8d81f40d8a3c = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Outfitters Stores\BI-Upload - Documents\Reporting\Combine\Kit Components.xlsx"), null, true),
				    Kit_Sheet = Source{[Item="Kit",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Kit_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Style", type text}, {"Quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

