table UK_Targets
	lineageTag: 8d2991c2-92cb-404f-800f-55f169b6f235

	column Code
		dataType: string
		lineageTag: b3f2106f-5006-4210-be7c-7c810a5b590c
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Shop
		dataType: string
		lineageTag: b189ff09-2a48-4e87-9d34-bf0410de4f66
		summarizeBy: none
		sourceColumn: Shop

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 3cc1dc7c-c2c9-484e-aad1-f424467e68fb
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 767a60a1-c436-4e59-a13d-e52f233fecdb
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Target
		dataType: int64
		formatString: 0
		lineageTag: 1199c089-14ed-4ee0-be44-02891dbf65e4
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		lineageTag: 87290160-bc8c-4984-b592-68fdfbb9e26e
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TGT(PKR)
		dataType: double
		lineageTag: 7b9bfca9-2e7e-49ff-96d5-fa4ce79b577b
		summarizeBy: sum
		sourceColumn: TGT(PKR)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Combine
		dataType: string
		lineageTag: ed753132-1895-46b3-a872-cf066f3320f2
		summarizeBy: none
		sourceColumn: Combine

		annotation SummarizationSetBy = Automatic

	column Rate-USD
		dataType: double
		lineageTag: fad61861-c644-4f6e-8ebc-8c5c56328717
		summarizeBy: sum
		sourceColumn: Rate-USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TGT(USD)
		dataType: double
		lineageTag: a3e16022-1f76-40b5-b1f9-694f659c1796
		summarizeBy: sum
		sourceColumn: TGT(USD)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column6
		dataType: string
		lineageTag: 9ca06cd7-cf74-4c28-8c6c-9e8bef9a8f02
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	partition UK_Targets = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Outfitters Stores\BI-Upload - Documents\PP DATA\COMBINE\Day wise Targets_UK.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Code", type text}, {"Shop", type text}, {"Brand", type text}, {"Date", type date}, {"Target", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Date"}, GBP_PKR, {"Date"}, "GBP_PKR", JoinKind.LeftOuter),
				    #"Expanded GBP_PKR" = Table.ExpandTableColumn(#"Merged Queries", "GBP_PKR", {"Price"}, {"Price"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded GBP_PKR", "TGT(PKR)", each [Target]*[Price]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"TGT(PKR)", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Combine", each [Shop]&"Ethnic-UK"),
				    #"Merged Queries1" = Table.NestedJoin(#"Added Custom1", {"Date"}, GBP_USD, {"Date"}, "GBP_USD", JoinKind.LeftOuter),
				    #"Expanded GBP_USD" = Table.ExpandTableColumn(#"Merged Queries1", "GBP_USD", {"Price"}, {"Price.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded GBP_USD",{{"Price.1", "Rate-USD"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns", "TGT(USD)", each [Target]*[#"Rate-USD"]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"TGT(USD)", type number}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

